#!/usr/bin/env node
/* =============================================================================
   build.mjs: builds the standalone Byman Cykler placeholder page
   =============================================================================

   WHAT THIS DOES (plain words)
   ----------------------------
   It reads three files and writes a finished web page into the folder build/:
     data/business.json   name, address, phone, email, opening hours, special hours
     data/brands.json     the brand logos, in the order they appear on the page
     design/copy-da.md    every Danish text on the page (the "## Strings" block)
   It also makes web-sized versions of the shop photo (build/img/) and copies the
   design tokens (design/tokens.css -> build/tokens.css).
   Nothing is downloaded and nothing is installed. Only Node is needed.

   What ends up in build/:
     index.html   GENERATED by this script. Don't edit it by hand: your change
                  would be lost the next time someone runs the build.
     tokens.css   GENERATED copy of design/tokens.css (the Press colours, fonts, sizes).
     styles.css   hand-written page styles (ui-spec.md). This script never touches it.
     app.js       hand-written script: "Åbent nu" status, today's row, special-hours
                  notice, pause button. This script never touches it.
     img/         GENERATED photo versions and PNG logo copies.
   The build/ folder only uses relative links, so it can be uploaded on its own.

   HOW TO RUN IT
   -------------
   Open Terminal and type ONE of these, then press Enter:
     node placeholder/build.mjs     (when you are in the Byman-cykler folder)
     node build.mjs                 (when you are in the placeholder folder)
   It prints what it did. If something is wrong in the data, it stops without
   changing the page and tells you (in Danish and English) what to fix.

   HOW TO ADD A BRAND
   ------------------
   1. Put the logo file in placeholder/assets/logos/. Best: an SVG that uses
      fill="currentColor". Also fine: a white or black PNG on a transparent background.
      Only use official logo files (the brand's own website or press kit).
   2. In data/brands.json, copy one existing entry (from { to }) and change at least
      "name", "slug" (short, lowercase, no spaces, e.g. "dt-swiss"), "logo" (the file
      path) and "scale" (1 = normal size; bigger number = bigger logo).
      The order in the file is the order on the page.
   3. Run the build again. With 12 or more logos the grid switches to 6 per row on
      wide screens by itself, and the "…og mange flere" box always fills the last row.

   HOW TO SWAP THE PHOTO
   ---------------------
   1. Put the new photo in placeholder/assets/img/ (JPEG or PNG). Ideal: landscape,
      daylight, at least 2400 px wide, ideally 3600 x 2025 (16:9), with the BYMAN sign
      and the door in the middle third of the picture.
   2. Change PHOTO_FILE below to the new file name.
   3. Change "photo.alt" in design/copy-da.md so it describes the NEW photo (it is
      read aloud to blind visitors and shown if the photo can't load).
      Tip: phone photos can hide the place and time they were taken. On the Mac, open the
      photo in Preview, choose Tools → Show Inspector → (i) → GPS → Remove Location Info.
      Only use a photo the shop owns (not from Google Maps, Street View or review sites).
   4. Run the build ON THE MAC (it uses the Mac's built-in "sips" tool to make the
      smaller AVIF and JPEG versions). The page then picks the layout by itself: a
      photo at least 2400 px wide and landscape fills the full width; a smaller photo
      is shown smaller, so it never looks blurry. The versions are kept in build/img/
      and reused, so a later build on a computer without "sips" still works.

   HOW TO ADD SPECIAL OPENING HOURS (holidays, stock-taking, ...)
   --------------------------------------------------------------
   In data/business.json, "specialHours" is a list. Add one entry per date:
       "specialHours": [
         { "date": "2026-12-24", "closed": true, "note": "God jul." },
         { "date": "2026-12-23", "open": "10:00", "close": "13:00", "closed": false }
       ]
   - "date" is YEAR-MONTH-DAY. Times are HH:MM with a colon (the page shows "10.00").
   - "note" is optional, a short Danish sentence.
   - From 14 days before the date, the page shows a notice above the hours table, and
     the "Åbent nu" status uses the special hours on that day. Then run the build.
   - Dates that have passed are left out automatically at the next build.

   FONTS
   -----
   The page uses the theme's own fonts, Instrument Serif and Space Mono, from
   assets/fonts/ (copied to build/fonts/). If a font can't load, the browser uses the
   closest system font (Bodoni 72 / Times New Roman and Menlo / Consolas). To change
   the font files, edit FONTS below.

   THE BYMAN LOGO (later)
   ----------------------
   There is no logo file yet, so the name is shown as text. When there is one, put it
   in assets/logos/ (SVG preferred) and set LOGO_FILE below, then run the build.

   BEFORE PUBLISHING THE PAGE: SET PAGE_URL
   ----------------------------------------
   PAGE_URL below is the page's public address. It is empty (null) until Søren has
   chosen where the standalone page will live. While it is empty, the build prints a
   warning and the page has: no canonical link, no og:url, and NO share picture
   (Facebook, Messenger and LinkedIn need a full https:// address for it, and so does
   Google's business data). Set it, e.g. PAGE_URL = 'https://www.example.dk/', and
   build again: the canonical link, og:url, og:image and the JSON-LD image then all
   use full https:// addresses. The address must start with https:// and end with
   "/" (or with the page name, e.g. ".../index.html").

   TEST SWITCHES FOR THE FINISHED PAGE (add to the address, e.g. index.html?now=...)
   ?now and ?special only work on your own computer (localhost, 127.0.0.1, *.localhost,
   or the file opened from disk). On the published page they are ignored, so nobody can
   share a link that shows fake opening hours.
     ?now=2026-10-10T13:30          pretend it is this time in Copenhagen
     ?special=2026-10-10,10:00,12:00  pretend there are special hours that day
     ?special=2026-10-10,closed       (repeat &special=... for more dates;
     ?special=2026-10-10,closed,Note  an optional note goes after the last comma)
     ?nojs=1                        show the page as it looks without JavaScript
                                    (works everywhere; it only shows the plain page)
   ========================================================================== */

/* ---------- SETTINGS: the only lines you normally change ---------- */

// The shop photo, relative to the placeholder/ folder. null = no photo (a red name band instead).
const PHOTO_FILE = 'assets/img/facade-placeholder.png';
// Which part of the photo to keep when it is cropped (full-width photo only). "50% 35%" = a bit above the middle.
const PHOTO_FOCUS = '50% 50%';
// The Byman logo file, relative to placeholder/ (SVG or PNG). null = show the name as text.
const LOGO_FILE = null;
// The page's final public address, e.g. 'https://www.example.dk/'. null = not known yet.
// MUST be set before publishing (see "BEFORE PUBLISHING" above): it gives the canonical link,
// og:url and the share picture. While null, the build warns and leaves the picture out.
const PAGE_URL = 'https://www.byman-cykler.dk/';   // Søren, 2026-10-09: the standalone page goes live here (www is primary)

// Web fonts: the real Press fonts, stored in assets/fonts/ (no Google request; Søren approved the files).
// Every file in assets/fonts/ (also the OFL licence .txt files) is copied to build/fonts/.
// preload: true = the browser fetches it straight away (used for most of the text).
const FONTS = [
  { family: 'Instrument Serif', weight: 400, file: 'instrument-serif-400-latin.woff2', preload: true },  // headings, big name
  { family: 'Space Mono', weight: 400, file: 'space-mono-400-latin.woff2', preload: true },              // all other text
  { family: 'Space Mono', weight: 700, file: 'space-mono-700-latin.woff2', preload: false },             // today's row only
];

/* ---------- Fixed values (change only with the designer) ---------- */
const TIME_ZONE = 'Europe/Copenhagen';  // the shop's clock; the status never uses the visitor's own time zone
const THEME_COLOR = '#ffffff';          // browser bar colour on phones: the Press page background
const JPEG_QUALITY = 82;                // ui-spec §4.4
const AVIF_QUALITY = 60;                // about the same look as JPEG 82, at roughly half the size
// Rules from design/ui-spec.md (section numbers in brackets)
const FULL_MIN_WIDTH = 2400;            // [4.3] full-width photo from this many pixels wide ...
const FULL_MIN_RATIO = 1.3;             // [4.3] ... and at least this landscape (4:3 passes)
const MAX_UPSCALE = 1.5;                // [4.2] a smaller photo is never shown bigger than 1.5x its pixels
const SRCSET_WIDTHS = [800, 1200, 1600, 2400, 3200]; // [4.4] never larger than the file
const BADGE_RATIO = 1.6;                // [5.3] logos narrower than 1.6:1 count as square badges
const MANY_BRANDS = 12;                 // [5.1] from 12 logos: the "many" grid
const NOTICE_DAYS = 14;                 // [6.5] special hours are announced 14 days ahead

/* ========================================================================== */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, unlinkSync, copyFileSync } from 'node:fs';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';

const ROOT = dirname(fileURLToPath(import.meta.url)); // the placeholder/ folder, wherever you run from
const OUT = join(ROOT, 'build');
const IMG = join(OUT, 'img');

const errors = [];
const warnings = [];
const fail = (da, en) => errors.push(`${da}\n      (${en})`);
const warn = (da, en) => warnings.push(`${da}\n      (${en})`);
const log = (s) => console.log(s);

function stopIfErrors() {
  if (!errors.length) return;
  console.error(`\nBYGGET STOPPEDE / BUILD STOPPED: ${errors.length} fejl. index.html er ikke ændret. / index.html was not changed.\n`);
  errors.forEach((e, i) => console.error(`  ${i + 1}. ${e}`));
  console.error('');
  process.exit(1);
}

/* ---------- Small helpers ---------- */

// Escape text for HTML (text and attribute values).
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
// JSON inside <script>: "<" is escaped so the text can never close the script tag.
const scriptJson = (o, pretty) => JSON.stringify(o, null, pretty ? 2 : 0).replace(/</g, '\\u003c');
const fill = (tpl, values) => tpl.replace(/\{(\w+)\}/g, (m, k) => (k in values ? values[k] : m));
const dk = (hhmm) => hhmm.replace(':', '.');           // "09:00" -> "09.00" (ui-spec §6.2)
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const TIME = /^([01]\d|2[0-3]):[0-5]\d$/;
const isUrl = (s) => typeof s === 'string' && /^https?:\/\/[^\s"<>]+$/.test(s);
const kb = (n) => `${(n / 1024).toFixed(1)} KB`;

function readText(rel) {
  const file = join(ROOT, rel);
  if (!existsSync(file)) { fail(`Filen mangler: ${rel}`, `Missing file: ${rel}`); return null; }
  return readFileSync(file, 'utf8');
}
function readJson(rel) {
  const text = readText(rel);
  if (text === null) return null;
  try { return JSON.parse(text); } catch (e) {
    fail(`${rel} er ikke gyldig JSON (tjek kommaer og anførselstegn): ${e.message}`, `${rel} is not valid JSON: ${e.message}`);
    return null;
  }
}

// Calendar maths at noon UTC, so summer time never shifts a date.
const utc = (ymd) => new Date(`${ymd}T12:00:00Z`);
const validYmd = (s) => typeof s === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(s) && utc(s).toISOString().slice(0, 10) === s;
function todayIn(tz) {
  const p = {};
  new Intl.DateTimeFormat('en-GB', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' })
    .formatToParts(new Date()).forEach((x) => { p[x.type] = x.value; });
  return `${p.year}-${p.month}-${p.day}`;
}

/* ---------- Image sizes, read in plain Node (works on Mac, Linux and Vercel) ---------- */

function imageInfo(buf) {
  // PNG: width and height are bytes 16-23. Colour type (byte 25) 4 or 6, or a tRNS chunk = has transparency.
  if (buf.length > 33 && buf.readUInt32BE(0) === 0x89504e47) {
    let alpha = buf[25] === 4 || buf[25] === 6;
    for (let i = 8; i + 8 <= buf.length && !alpha;) {
      const len = buf.readUInt32BE(i), type = buf.toString('latin1', i + 4, i + 8);
      if (type === 'tRNS') alpha = true;
      if (type === 'IDAT' || type === 'IEND') break;
      i += 12 + len;
    }
    return { type: 'png', width: buf.readUInt32BE(16), height: buf.readUInt32BE(20), alpha, orientation: 1 };
  }
  // JPEG: walk the markers to the "start of frame" (SOF). Also read the EXIF rotation flag.
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let i = 2, orientation = 1;
    while (i + 9 < buf.length) {
      if (buf[i] !== 0xff) return null;
      const m = buf[i + 1];
      if (m === 0xff) { i++; continue; }
      if (m === 0x01 || (m >= 0xd0 && m <= 0xd8)) { i += 2; continue; }
      const len = buf.readUInt16BE(i + 2);
      if (m === 0xe1 && buf.toString('latin1', i + 4, i + 10) === 'Exif\0\0') orientation = exifOrientation(buf, i + 10) || 1;
      if (m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) {
        return { type: 'jpeg', height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7), alpha: false, orientation };
      }
      i += 2 + len;
    }
  }
  return null;
}
function exifOrientation(buf, t) {
  try {
    const le = buf.toString('latin1', t, t + 2) === 'II';
    const u16 = (o) => (le ? buf.readUInt16LE(o) : buf.readUInt16BE(o));
    const u32 = (o) => (le ? buf.readUInt32LE(o) : buf.readUInt32BE(o));
    const ifd = t + u32(t + 4), n = u16(ifd);
    for (let k = 0; k < n; k++) { const e = ifd + 2 + k * 12; if (u16(e) === 0x0112) return u16(e + 8); }
  } catch { /* no readable EXIF: treat as upright */ }
  return 1;
}

/* ---------- 1. Read and check the inputs ---------- */

const business = readJson('data/business.json');
const brands = readJson('data/brands.json');
const copyMd = readText('design/copy-da.md');
const tokensCss = readText('design/tokens.css');
for (const f of ['build/styles.css', 'build/app.js']) {
  if (!existsSync(join(ROOT, f))) fail(`${f} mangler. Den er håndskrevet og laves ikke af bygget; hent den fra git.`, `${f} is missing. It is hand-written, not generated; restore it from git.`);
}
stopIfErrors();

// --- Strings from design/copy-da.md, "## Strings" block: one "key = value" per line ---
const S = {};
{
  const at = copyMd.search(/^## Strings[ \t]*$/m);
  const block = at < 0 ? null : copyMd.slice(at).match(/```[^\n]*\n([\s\S]*?)```/);
  if (!block) fail('design/copy-da.md: fandt ikke "## Strings" med en ```-blok under.', 'design/copy-da.md: no "## Strings" heading followed by a ``` block.');
  else block[1].split('\n').forEach((line, n) => {
    if (!line.trim() || line.trim().startsWith('#')) return;
    const i = line.indexOf(' = ');
    if (i < 0) { fail(`design/copy-da.md, Strings linje ${n + 1}: mangler " = ": "${line.trim()}"`, `Strings line ${n + 1} has no " = "`); return; }
    const key = line.slice(0, i).trim(), value = line.slice(i + 3).trim();
    if (key in S) warn(`design/copy-da.md: nøglen "${key}" står to gange; den sidste bruges.`, `Duplicate key "${key}"; the last one wins.`);
    S[key] = value;
  });
}
// Every key the page needs, with the {placeholders} it must contain.
const REQUIRED_STRINGS = {
  'meta.title': [], 'meta.description': [], 'hero.eyebrow': [], 'hero.headline': [], 'hero.scroll.pause': [], 'hero.intro': [],
  'hours.heading': [], 'hours.special.heading': [], 'hours.status.open': ['close'], 'hours.status.opensLater': ['open'],
  'hours.status.opensTomorrow': ['open'], 'hours.status.opensOn': ['day', 'open'], 'hours.status.closedToday': [],
  'hours.notice.special': ['date', 'hours'], 'hours.source': [], 'hours.closed': [], 'hours.today': [],
  'day.monday': [], 'day.tuesday': [], 'day.wednesday': [], 'day.thursday': [], 'day.friday': [], 'day.saturday': [], 'day.sunday': [],
  'contact.heading': [], 'contact.phone.label': [], 'contact.email.label': [], 'contact.email.missing': [], 'address.heading': [],
  'cta.call': [], 'cta.directions': [], 'cta.write': [], 'brands.heading': [], 'brands.intro': [], 'brands.more': [],
  'footer.text': [], 'photo.alt': [],
};
for (const [key, holes] of Object.entries(REQUIRED_STRINGS)) {
  if (!S[key]) { fail(`design/copy-da.md mangler teksten "${key}" i ## Strings.`, `Missing string key "${key}".`); continue; }
  for (const h of holes) if (!S[key].includes(`{${h}}`)) fail(`design/copy-da.md: "${key}" skal indeholde {${h}}.`, `String "${key}" must contain {${h}}.`);
}

// --- FONTS (setting above): the files must be in assets/fonts/ and be real WOFF2 files ---
const FONT_DIR = join(ROOT, 'assets/fonts');
for (const f of FONTS) {
  const file = join(FONT_DIR, f.file);
  if (!existsSync(file)) fail(`FONTS i build.mjs: skriftfilen findes ikke: assets/fonts/${f.file}`, `Missing font file: assets/fonts/${f.file}`);
  else if (readFileSync(file).toString('latin1', 0, 4) !== 'wOF2') fail(`assets/fonts/${f.file} er ikke en WOFF2-fil.`, `${f.file} is not a WOFF2 file.`);
}

// --- PAGE_URL (setting above) ---
if (PAGE_URL != null && !/^https:\/\/[^\s"<>?#]+(\/|\.html)$/.test(PAGE_URL)) fail(`PAGE_URL i build.mjs skal starte med https:// og slutte med "/" (eller ".html"). Nu: "${PAGE_URL}"`, 'PAGE_URL must start with https:// and end with "/" or ".html".');
if (!PAGE_URL) warn('PAGE_URL er ikke sat i build.mjs. Siden har derfor intet canonical-link og intet delingsbillede (Facebook/Google). Sæt PAGE_URL til sidens offentlige adresse, før siden udgives.', 'PAGE_URL is not set: no canonical link, no og:url, no share image. Set it before going live.');

// --- business.json ---
const b = business;
const DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']; // table order
const JS_DAY = { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }; // JavaScript getDay()
const SCHEMA_DAY = { monday: 'Monday', tuesday: 'Tuesday', wednesday: 'Wednesday', thursday: 'Thursday', friday: 'Friday', saturday: 'Saturday', sunday: 'Sunday' };

// A fact that is missing is shown as a visible [MANGLER: ...] and listed, never guessed.
const missing = [];
function fact(value, label) {
  if (typeof value === 'string' ? value.trim() : value != null) return value;
  missing.push(label);
  return `[MANGLER: ${label}]`;
}
const name = fact(b.name, 'butikkens navn');
const street = fact(b.address?.street, 'gade og nummer');
const postalCode = fact(b.address?.postalCode, 'postnummer');
const city = fact(b.address?.city, 'by');
const phoneDisplay = fact(b.phone?.display, 'telefonnummer');
const phoneE164 = b.phone?.e164 || '';
if (phoneE164 && !/^\+\d{8,15}$/.test(phoneE164)) fail(`business.json: phone.e164 skal se sådan ud: +4512345678 (nu: "${phoneE164}").`, 'phone.e164 must look like +4512345678.');
const email = (b.email || '').trim();
if (email && !/^[^\s@<>"]+@[^\s@<>"]+\.[a-z]{2,}$/i.test(email)) fail(`business.json: e-mailen ser forkert ud: "${email}".`, `Email looks wrong: "${email}".`);
const mapsUrl = b.google?.mapsUrl || '';
if (!isUrl(mapsUrl)) fail('business.json: google.mapsUrl mangler eller er ikke en https-adresse (bruges til "Find vej").', 'google.mapsUrl is missing or not a URL.');
if (b.website && !isUrl(b.website)) fail(`business.json: website er ikke en gyldig adresse: "${b.website}".`, 'website is not a valid URL.');
if (b.geo && (typeof b.geo.lat !== 'number' || typeof b.geo.lng !== 'number')) fail('business.json: geo.lat og geo.lng skal være tal.', 'geo.lat and geo.lng must be numbers.');
if (b.cvr && !/^\d{8}$/.test(b.cvr)) fail(`business.json: cvr skal være 8 cifre (nu: "${b.cvr}").`, 'cvr must be 8 digits.');
const SOCIAL_LABELS = { instagram: 'Instagram', facebook: 'Facebook', strava: 'Strava' }; // brand names, not translated
const socials = Object.entries(b.social || {}).filter(([, url]) => url);
for (const [k, url] of socials) {
  if (!isUrl(url)) fail(`business.json: social.${k} er ikke en gyldig adresse: "${url}".`, `social.${k} is not a URL.`);
  if (!SOCIAL_LABELS[k]) fail(`business.json: ukendt socialt medie "${k}". Tilføj det i SOCIAL_LABELS i build.mjs.`, `Unknown social "${k}"; add it to SOCIAL_LABELS.`);
}

// Weekly hours: all 7 days, once each, "HH:MM", open before close.
const week = {};
if (!Array.isArray(b.openingHours)) fail('business.json: "openingHours" skal være en liste med 7 dage.', '"openingHours" must be a list of 7 days.');
else for (const [i, d] of b.openingHours.entries()) {
  const where = `business.json openingHours[${i}]`;
  if (!DAYS.includes(d.day)) { fail(`${where}: ukendt dag "${d.day}" (brug monday … sunday).`, `Unknown day "${d.day}".`); continue; }
  if (week[d.day]) { fail(`${where}: ${d.day} står to gange.`, `${d.day} appears twice.`); continue; }
  if (d.closed === true) { week[d.day] = { closed: true }; continue; }
  if (d.closed !== false) fail(`${where} (${d.day}): "closed" skal være true eller false.`, '"closed" must be true or false.');
  if (!TIME.test(d.open || '') || !TIME.test(d.close || '')) { fail(`${where} (${d.day}): tider skal skrives "HH:MM", fx "09:00" (nu: "${d.open}"–"${d.close}").`, 'Times must be "HH:MM".'); continue; }
  if (d.open >= d.close) { fail(`${where} (${d.day}): åbner (${d.open}) skal være før lukker (${d.close}).`, 'Open must be before close (no hours past midnight).'); continue; }
  week[d.day] = { open: d.open, close: d.close };
}
for (const d of DAYS) if (Array.isArray(b.openingHours) && !week[d] && !b.openingHours.some((x) => x.day === d)) fail(`business.json: openingHours mangler ${d}.`, `openingHours is missing ${d}.`);

// Special hours: { date, open, close, closed, note }. Past dates are dropped.
const buildDay = todayIn(TIME_ZONE);
const special = [];
if (b.specialHours != null && !Array.isArray(b.specialHours)) fail('business.json: "specialHours" skal være en liste: [ ].', '"specialHours" must be a list.');
else for (const [i, s] of (b.specialHours || []).entries()) {
  const where = `business.json specialHours[${i}]`;
  if (!validYmd(s.date)) { fail(`${where}: "date" skal være en rigtig dato som "2026-12-24" (nu: "${s.date}").`, 'date must be YYYY-MM-DD.'); continue; }
  if ((b.specialHours || []).slice(0, i).some((x) => x.date === s.date)) { fail(`${where}: ${s.date} står to gange.`, 'Duplicate date.'); continue; }
  if (s.note != null && typeof s.note !== 'string') fail(`${where}: "note" skal være tekst.`, 'note must be text.');
  let entry;
  if (s.closed === true) entry = { date: s.date, closed: true };
  else if (!TIME.test(s.open || '') || !TIME.test(s.close || '')) { fail(`${where} (${s.date}): skriv "closed": true, eller "open"/"close" som "HH:MM".`, 'Use "closed": true, or "open"/"close" as "HH:MM".'); continue; }
  else if (s.open >= s.close) { fail(`${where} (${s.date}): åbner skal være før lukker.`, 'open must be before close.'); continue; }
  else entry = { date: s.date, open: s.open, close: s.close, closed: false };
  if (s.note && s.note.trim()) entry.note = s.note.trim();
  if (s.date < buildDay) { warn(`Særlige åbningstider ${s.date} er overstået og er udeladt. Du kan slette dem i business.json.`, `Special hours ${s.date} are in the past and were left out.`); continue; }
  special.push(entry);
}
special.sort((x, y) => (x.date < y.date ? -1 : 1));

// --- brands.json ---
if (!Array.isArray(brands) || !brands.length) fail('data/brands.json skal være en liste med mindst ét mærke.', 'brands.json must be a non-empty list.');
const slugs = new Set();
for (const [i, br] of (Array.isArray(brands) ? brands : []).entries()) {
  const where = `data/brands.json [${i}] (${br.name || '?'})`;
  if (!br.name || typeof br.name !== 'string') fail(`${where}: "name" mangler.`, 'name is missing.');
  if (!/^[a-z0-9-]+$/.test(br.slug || '')) fail(`${where}: "slug" skal være små bogstaver, tal og bindestreg (nu: "${br.slug}").`, 'slug must be lowercase letters, digits and hyphens.');
  else if (slugs.has(br.slug)) fail(`${where}: slug "${br.slug}" bruges allerede.`, 'Duplicate slug.');
  slugs.add(br.slug);
  if (typeof br.scale !== 'number' || !(br.scale > 0 && br.scale <= 3)) fail(`${where}: "scale" skal være et tal mellem 0 og 3 (nu: ${br.scale}).`, 'scale must be a number between 0 and 3.');
  if (!br.logo || !/\.(svg|png)$/i.test(br.logo)) fail(`${where}: "logo" skal pege på en .svg- eller .png-fil (nu: "${br.logo}").`, 'logo must be an .svg or .png file.');
  else if (!existsSync(join(ROOT, br.logo))) fail(`${where}: logo-filen findes ikke: ${br.logo}`, `Missing logo file: ${br.logo}`);
}
stopIfErrors();

/* ---------- 2. Logos ---------- */

function parseAttrs(s) {
  const a = {};
  for (const m of s.matchAll(/([\w:.-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g)) a[m[1]] = m[2] ?? m[3];
  return a;
}
const escRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Turn an SVG file into safe inline markup that takes the text colour (currentColor).
function inlineSvg(rel, { label, cls, style, idPrefix }) {
  let s = readFileSync(join(ROOT, rel), 'utf8')
    .replace(/<\?xml[\s\S]*?\?>/g, '').replace(/<!DOCTYPE[\s\S]*?>/gi, '').replace(/<!--[\s\S]*?-->/g, '').trim();
  const m = s.match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>$/i);
  if (!m) { fail(`${rel}: kunne ikke læse SVG-filen (starter den med <svg …>?).`, `${rel}: not a readable SVG.`); return null; }
  const attrs = parseAttrs(m[1]);
  let inner = m[2];
  // Safety: an inline SVG becomes part of the page, so no scripts, styles or outside links.
  if (/<script\b|<foreignObject\b|\son\w+\s*=|javascript:/i.test(s)) { fail(`${rel}: SVG-filen indeholder script eller event-kode og bruges ikke.`, `${rel}: contains scripts.`); return null; }
  if (/<style\b/i.test(inner)) { fail(`${rel}: SVG-filen har en <style>-blok, som ville ændre resten af siden. Fjern den og brug fill="currentColor".`, `${rel}: has a <style> block that would leak into the page.`); return null; }
  if (/\b(?:xlink:)?href\s*=\s*["'](?!#)/i.test(inner)) { fail(`${rel}: SVG-filen henter noget udefra (href). Det er ikke tilladt.`, `${rel}: references an outside file.`); return null; }
  // Fixed colours would not follow the page colour: warn.
  const fixed = [...s.matchAll(/\b(?:fill|stroke)\s*[=:]\s*"?\s*(#[0-9a-f]{3,8}|rgb[^;"]*|[a-z]+)/gi)].map((x) => x[1]).filter((v) => !/^(currentColor|none|inherit|evenodd|nonzero)$/i.test(v));
  if (fixed.length) warn(`${rel}: logoet har faste farver (${[...new Set(fixed)].join(', ')}), så det bliver ikke ensfarvet. Brug fill="currentColor".`, `${rel}: has fixed colours.`);
  // <title>/<desc> are replaced by our own label; ids get a unique prefix so two SVGs can never clash.
  inner = inner.replace(/<title\b[\s\S]*?<\/title>/gi, '').replace(/<desc\b[\s\S]*?<\/desc>/gi, '');
  for (const [, id] of inner.matchAll(/\bid\s*=\s*"([^"]+)"/g)) {
    const nid = `${idPrefix}-${id}`, e = escRe(id);
    inner = inner.replace(new RegExp(`(\\bid\\s*=\\s*")${e}"`, 'g'), `$1${nid}"`)
      .replace(new RegExp(`url\\(\\s*#${e}\\s*\\)`, 'g'), `url(#${nid})`)
      .replace(new RegExp(`(href\\s*=\\s*")#${e}"`, 'g'), `$1#${nid}"`);
  }
  inner = inner.replace(/>\s+</g, '><').trim();
  // The shape: from viewBox, else width/height.
  let vb = (attrs.viewBox || '').trim().split(/[\s,]+/).map(Number);
  if (vb.length !== 4 || vb.some((n) => !Number.isFinite(n)) || !(vb[2] > 0 && vb[3] > 0)) {
    const w = parseFloat(attrs.width), h = parseFloat(attrs.height);
    if (!(w > 0 && h > 0)) { fail(`${rel}: SVG-filen har hverken viewBox eller width/height.`, `${rel}: no viewBox or size.`); return null; }
    vb = [0, 0, w, h];
  }
  const keep = ['fill', 'fill-rule', 'clip-rule', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin', 'preserveAspectRatio']
    .filter((k) => attrs[k] != null).map((k) => ` ${k}="${esc(attrs[k])}"`).join('');
  const ratio = vb[2] / vb[3];
  return {
    ratio,
    html: `<svg class="${typeof cls === 'function' ? cls(ratio) : cls}" viewBox="${vb.join(' ')}"${keep} role="img" aria-label="${esc(label)}" focusable="false"${style ? ` style="${style(ratio)}"` : ''}>${inner}</svg>`,
  };
}

mkdirSync(IMG, { recursive: true });
const keepImg = new Set();     // generated files in build/img that belong to this build
const pngLogoFiles = [];

const brandItems = brands.map((br) => {
  const style = (r) => `--scale:${br.scale};--ratio:${r.toFixed(4)}`;
  const cls = (r) => `logo${r < BADGE_RATIO ? ' logo--badge' : ''}`;
  if (/\.svg$/i.test(br.logo)) {
    const svg = inlineSvg(br.logo, { label: br.name, cls, style, idPrefix: `logo-${br.slug}` });
    return svg ? `<li class="cell brand">${svg.html}</li>` : '';
  }
  // PNG: shown as a CSS mask filled with the text colour (ui-spec §5.5). The file is copied into build/img/.
  const buf = readFileSync(join(ROOT, br.logo));
  const info = imageInfo(buf);
  if (!info || info.type !== 'png') { fail(`${br.logo}: kunne ikke læse PNG-filen.`, `${br.logo}: unreadable PNG.`); return ''; }
  if (!info.alpha) fail(`${br.logo}: PNG-logoet har ingen gennemsigtig baggrund, så det ville blive en massiv firkant. Brug en PNG med gennemsigtig baggrund.`, `${br.logo}: PNG has no transparency.`);
  const file = `logo-${br.slug}.png`;
  copyFileSync(join(ROOT, br.logo), join(IMG, file));
  keepImg.add(file); pngLogoFiles.push(file);
  const r = info.width / info.height, url = `img/${file}`;
  // The <img> inside is only for old browsers without CSS masks. loading="lazy" keeps it from downloading when hidden.
  return `<li class="cell brand"><span class="${cls(r)} logo--png" role="img" aria-label="${esc(br.name)}" style="${style(r)};-webkit-mask-image:url(${url});mask-image:url(${url})"><img src="${url}" alt="" width="${info.width}" height="${info.height}" loading="lazy"></span></li>`;
});
const n = brands.length;
const span = (c) => c - (n % c);     // "…og mange flere" fills the rest of the last row (ui-spec §5.4)
brandItems.push(`<li class="cell brand brand--more" style="--span-2:${span(2)};--span-4:${span(4)};--span-6:${span(6)}"><p>${esc(S['brands.more'])}</p></li>`);

// The Byman logo for the wordmark row (optional).
let wordmark = `<p class="wordmark" translate="no">${esc(name)}</p>`;
if (LOGO_FILE) {
  if (!existsSync(join(ROOT, LOGO_FILE))) fail(`LOGO_FILE i build.mjs peger på en fil, der ikke findes: ${LOGO_FILE}`, `LOGO_FILE not found: ${LOGO_FILE}`);
  else if (/\.svg$/i.test(LOGO_FILE)) {
    const svg = inlineSvg(LOGO_FILE, { label: name, cls: 'wordmark__logo', idPrefix: 'site-logo' });
    if (svg) wordmark = svg.html;
  } else if (/\.png$/i.test(LOGO_FILE)) {
    const info = imageInfo(readFileSync(join(ROOT, LOGO_FILE)));
    copyFileSync(join(ROOT, LOGO_FILE), join(IMG, 'site-logo.png')); keepImg.add('site-logo.png');
    wordmark = `<img class="wordmark__logo" src="img/site-logo.png" alt="${esc(name)}" width="${info.width}" height="${info.height}">`;
  } else fail('LOGO_FILE skal være en .svg- eller .png-fil.', 'LOGO_FILE must be .svg or .png.');
}
stopIfErrors();

/* ---------- 3. Photo: size, layout rule and web versions ---------- */

let photo = null;
if (!PHOTO_FILE) warn('Intet foto valgt (PHOTO_FILE = null): siden viser navnet med stor rød skrift i stedet.', 'No photo: the name is shown in large red text instead.');
else {
  const src = join(ROOT, PHOTO_FILE);
  if (!existsSync(src)) { fail(`PHOTO_FILE i build.mjs peger på en fil, der ikke findes: ${PHOTO_FILE}`, `PHOTO_FILE not found: ${PHOTO_FILE}`); stopIfErrors(); }
  const buf = readFileSync(src);
  const info = imageInfo(buf);
  if (!info) { fail(`${PHOTO_FILE}: kun JPEG og PNG kan bruges.`, `${PHOTO_FILE}: only JPEG and PNG are supported.`); stopIfErrors(); }
  if (info.orientation > 1) { fail(`${PHOTO_FILE}: fotoet er gemt "på siden" med en rotations-markering (EXIF ${info.orientation}). Åbn det i Billedfremviser (Preview), vælg Arkiv → Eksporter som JPEG, og byg igen.`, 'The photo has an EXIF rotation flag; export it again upright.'); stopIfErrors(); }
  const { width: w, height: h } = info;
  const mode = w >= FULL_MIN_WIDTH && w / h >= FULL_MIN_RATIO ? 'full' : 'contained';
  const widths = SRCSET_WIDTHS.filter((x) => x <= w);
  if (w < SRCSET_WIDTHS.at(-1) && !widths.includes(w)) widths.push(w);
  widths.sort((x, y) => x - y);
  // The file name carries a fingerprint of the photo, so a new photo never shows an old cached one.
  const hash = createHash('sha1').update(buf).update(`v2 q${JPEG_QUALITY}/${AVIF_QUALITY}`).digest('hex').slice(0, 8);

  let sipsOk = false, avifOk = false;
  try { avifOk = /avif\s+Writable/i.test(execFileSync('sips', ['--formats'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })); sipsOk = true; } catch { /* no sips (Linux, Vercel) */ }
  const sips = (args) => execFileSync('sips', args, { stdio: 'ignore' });
  const made = { jpeg: [], avif: [] };
  for (const x of widths) {
    // Every version gets EVEN width and height (at most 1px is cropped off, never stretched).
    // Why: from about 1000px the Mac writes AVIF as a grid of 512px tiles, and browsers refuse to
    // show such a grid when a side is odd (MIAF rule for 4:2:0 colour). Measured: 1600x1205 = blank.
    const fw = x - (x % 2);
    const todo = [['jpeg', 'jpg', JPEG_QUALITY], ['avif', 'avif', AVIF_QUALITY]]
      .filter(([fmt, ext]) => !existsSync(join(IMG, `photo-${hash}-${fw}.${ext}`)) && sipsOk && (fmt !== 'avif' || avifOk));
    if (todo.length) {
      const tmp = join(IMG, `.tmp-photo-${hash}-${fw}.png`);   // lossless in-between step
      sips(['-s', 'format', 'png', ...(x < w ? ['--resampleWidth', String(x)] : []), src, '--out', tmp]);
      const t = imageInfo(readFileSync(tmp));
      if (t.width % 2 || t.height % 2) sips(['-c', String(t.height - (t.height % 2)), String(t.width - (t.width % 2)), tmp]);
      for (const [fmt, ext, q] of todo) sips(['-s', 'format', fmt, '-s', 'formatOptions', String(q), tmp, '--out', join(IMG, `photo-${hash}-${fw}.${ext}`)]);
      unlinkSync(tmp);
    }
    for (const [fmt, ext] of [['jpeg', 'jpg'], ['avif', 'avif']]) {
      const file = `photo-${hash}-${fw}.${ext}`;
      if (existsSync(join(IMG, file))) { keepImg.add(file); made[fmt].push(fw); }
    }
  }
  let fallback = null;
  if (!made.jpeg.length) {
    // No Mac: use the original file as it is (one size). Make the versions on the Mac before publishing.
    fallback = `photo-${hash}-${w}.${info.type === 'png' ? 'png' : 'jpg'}`;
    copyFileSync(src, join(IMG, fallback)); keepImg.add(fallback);
    warn('"sips" findes ikke her (kun på Mac), så fotoet bruges i original størrelse uden AVIF. Byg på Mac’en før udgivelse.', 'sips not available: the original photo is used as-is. Build on the Mac before publishing.');
  } else if (!made.avif.length) warn('Kunne ikke lave AVIF-versioner af fotoet; kun JPEG bruges.', 'Could not write AVIF; JPEG only.');

  const set = (fmt, ext) => made[fmt].map((x) => `img/photo-${hash}-${x}.${ext} ${x}w`).join(', ');
  const photoCap = Math.floor(w * MAX_UPSCALE);
  const pick = (max) => { const list = made.jpeg.length ? made.jpeg : [w]; return list.filter((x) => x <= max).at(-1) ?? list[0]; };
  const jpegFile = (x) => (fallback && !made.jpeg.length ? fallback : `photo-${hash}-${x}.jpg`);
  const srcW = pick(1600), ogW = pick(1200);
  const ogInfo = imageInfo(readFileSync(join(IMG, jpegFile(ogW))));
  const srcInfo = imageInfo(readFileSync(join(IMG, jpegFile(srcW))));   // <img width/height> = the real file
  photo = {
    w, h, mode, cap: photoCap, widths: made.jpeg.length ? made.jpeg : [w], hash, srcW,
    ratio: `${w} / ${h}`,
    ratioMobile: w / h > 1.5 ? '3 / 2' : `${w} / ${h}`,
    sizes: mode === 'full'
      ? '(min-width: 1024px) calc(100vw - 28px), calc(100vw - 14px)'
      : `(min-width: 1024px) min(calc(100vw - 28px), ${photoCap}px), min(calc(100vw - 14px), ${photoCap}px)`,
    avifSrcset: set('avif', 'avif'),
    jpegSrcset: made.jpeg.length ? set('jpeg', 'jpg') : `img/${fallback} ${w}w`,
    src: `img/${jpegFile(srcW)}`, imgW: srcInfo.width, imgH: srcInfo.height,
    og: { url: `img/${jpegFile(ogW)}`, w: ogInfo.width, h: ogInfo.height },
    formats: [made.avif.length && 'AVIF', made.jpeg.length ? 'JPEG' : info.type.toUpperCase()].filter(Boolean),
  };
}

// Remove generated images from earlier builds that are no longer used.
for (const f of readdirSync(IMG)) {
  if (/^(photo-.+\.(jpg|avif|png)|\.tmp-photo-.+\.png|logo-.+\.png|site-logo\.png)$/.test(f) && !keepImg.has(f)) unlinkSync(join(IMG, f));
}

/* ---------- 4. Hours: table, notice, data for app.js, JSON-LD ---------- */

const dayName = (d) => S[`day.${d}`];
const JS_DAY_NAMES = Object.keys(JS_DAY).sort((x, y) => JS_DAY[x] - JS_DAY[y]).map(dayName); // [søndag, mandag, …]
const monthFmt = new Intl.DateTimeFormat('da-DK', { month: 'long', timeZone: 'UTC' });
const MONTHS = [...Array(12)].map((_, m) => monthFmt.format(new Date(Date.UTC(2026, m, 15)))); // januar … december
const longDate = (ymd) => { const d = utc(ymd); return `${JS_DAY_NAMES[d.getUTCDay()]} ${d.getUTCDate()}. ${MONTHS[d.getUTCMonth()]}`; };
const timeRange = (o, c) => `<time datetime="${o}">${dk(o)}</time>–<time datetime="${c}">${dk(c)}</time>`;
const specialHoursText = (x) => (x.closed ? S['hours.closed'] : `${dk(x.open)}–${dk(x.close)}`);   // table cells: "Lukket"
const specialHoursInline = (x) => (x.closed ? S['hours.closed'].charAt(0).toLowerCase() + S['hours.closed'].slice(1) : specialHoursText(x)); // after a colon: "lukket" (QA S5)

const hoursRows = DAYS.map((d) => {
  const h = week[d];
  return h.closed
    ? `<tr data-day="${JS_DAY[d]}" data-closed><th scope="row">${esc(cap(dayName(d)))}</th><td>${esc(S['hours.closed'])}</td></tr>`
    : `<tr data-day="${JS_DAY[d]}" data-open="${h.open}" data-close="${h.close}"><th scope="row">${esc(cap(dayName(d)))}</th><td>${timeRange(h.open, h.close)}</td></tr>`;
}).join('\n          ');

// Without JavaScript the notice lists every coming special date (ui-spec §6.5). app.js then narrows it to 14 days.
function noticeHtml(list) {
  if (list.length === 1) {
    const x = list[0];
    return `<p>${esc(fill(S['hours.notice.special'], { date: longDate(x.date), hours: specialHoursInline(x) }))}${x.note ? `. ${esc(x.note)}` : ''}</p>`;
  }
  return `<p class="label notice__title">${esc(S['hours.special.heading'])}</p><table class="table notice__table"><tbody>${list.map((x) =>
    `<tr><th scope="row">${esc(cap(longDate(x.date)))}</th><td>${esc(specialHoursText(x))}</td></tr>${x.note ? `<tr class="notice__note"><td colspan="2">${esc(x.note)}</td></tr>` : ''}`).join('')}</tbody></table>`;
}
const notice = special.length
  ? `<div class="notice" id="notice" role="note">${noticeHtml(special)}</div>`
  : '<div class="notice" id="notice" role="note" hidden></div>';

// Data for app.js. The weekly hours are read from the table above (as on Shopify); special hours and texts come from here.
const hoursData = {
  timeZone: TIME_ZONE,
  noticeDays: NOTICE_DAYS,
  special,
  strings: {
    open: S['hours.status.open'], opensLater: S['hours.status.opensLater'], opensTomorrow: S['hours.status.opensTomorrow'],
    opensOn: S['hours.status.opensOn'], closedToday: S['hours.status.closedToday'], notice: S['hours.notice.special'],
    specialHeading: S['hours.special.heading'], closed: S['hours.closed'], today: S['hours.today'],
    days: JS_DAY_NAMES, months: MONTHS,
  },
};

// schema.org BikeStore for Google (ui-spec / ux-research §4). Same values as the page, all from business.json.
// Share picture and Google image need full https:// addresses (QA S4): without PAGE_URL they are left out.
const abs = (u) => (PAGE_URL ? new URL(u, PAGE_URL).href : null);
const groups = [];
for (const d of DAYS) {
  const h = week[d];
  if (h.closed) continue;     // days that aren't listed count as closed
  const g = groups.find((x) => x.opens === h.open && x.closes === h.close);
  if (g) g.dayOfWeek.push(SCHEMA_DAY[d]); else groups.push({ dayOfWeek: [SCHEMA_DAY[d]], opens: h.open, closes: h.close });
}
const ld = {
  '@context': 'https://schema.org',
  '@type': 'BikeStore',
  name: b.name || undefined,
  legalName: b.legalName || undefined,
  url: PAGE_URL || b.website || undefined,   // the page's own address once known, else the shop's website
  image: photo && PAGE_URL ? abs(photo.og.url) : undefined,
  telephone: phoneE164 || undefined,
  email: email || undefined,
  address: {
    '@type': 'PostalAddress',
    streetAddress: b.address?.street || undefined, postalCode: b.address?.postalCode || undefined,
    addressLocality: b.address?.city || undefined, addressCountry: b.address?.country || undefined,
  },
  geo: b.geo ? { '@type': 'GeoCoordinates', latitude: b.geo.lat, longitude: b.geo.lng } : undefined,
  hasMap: mapsUrl,
  openingHoursSpecification: [
    ...groups.map((g) => ({ '@type': 'OpeningHoursSpecification', dayOfWeek: g.dayOfWeek.length === 1 ? g.dayOfWeek[0] : g.dayOfWeek, opens: g.opens, closes: g.closes })),
    // Special dates: a closed day is written as opens = closes = 00:00 (Google's convention).
    ...special.map((x) => ({ '@type': 'OpeningHoursSpecification', validFrom: x.date, validThrough: x.date, opens: x.closed ? '00:00' : x.open, closes: x.closed ? '00:00' : x.close })),
  ],
  sameAs: socials.map(([, u]) => u),
};

/* ---------- 5. The page ---------- */

const tel = phoneE164 ? `tel:${phoneE164}` : '';
const phoneLink = (cls) => (tel ? `<a class="${cls}" href="${esc(tel)}">${esc(phoneDisplay)}</a>` : esc(phoneDisplay));
const mailLink = (cls) => `<a class="${cls}" href="mailto:${esc(email)}">${esc(email)}</a>`;
const scrollText = `${name}.`;   // the big moving name on the photo: "Byman Cykler."

const heroHtml = photo
  ? `<section class="sec hero hero--${photo.mode}" id="hero" style="--photo-ratio: ${photo.ratio}; --photo-ratio-mobile: ${photo.ratioMobile}; --photo-cap: ${photo.cap}px; --photo-focus: ${esc(PHOTO_FOCUS)}">
    <div class="hero__frame">
      <picture>
        ${photo.avifSrcset ? `<source type="image/avif" srcset="${photo.avifSrcset}" sizes="${photo.sizes}">` : ''}
        <img src="${photo.src}" srcset="${photo.jpegSrcset}" sizes="${photo.sizes}" width="${photo.imgW}" height="${photo.imgH}" alt="${esc(S['photo.alt'])}" fetchpriority="high" decoding="async">
      </picture>
      <div class="hero__scroll" aria-hidden="true" translate="no"><div class="hero__track">${`<span>${esc(scrollText)}</span>`.repeat(12)}</div></div>
      <button class="hero__pause" type="button" aria-pressed="false" aria-label="${esc(S['hero.scroll.pause'])}"><i aria-hidden="true"></i></button>
    </div>
  </section>`
  : `<div class="sec name-band" aria-hidden="true" translate="no">${esc(scrollText)}</div>`;

const ctas = [
  tel ? `<div class="cell"><a class="btn btn--primary" href="${esc(tel)}">${esc(S['cta.call'])}</a></div>` : '',
  `<div class="cell"><a class="btn" href="${esc(mapsUrl)}">${esc(S['cta.directions'])}</a></div>`,
  email ? `<div class="cell"><a class="btn" href="mailto:${esc(email)}">${esc(S['cta.write'])}</a></div>` : '',
].filter(Boolean);

const head = [
  `<meta charset="utf-8">`,
  `<meta name="viewport" content="width=device-width, initial-scale=1">`,
  `<title>${esc(S['meta.title'])}</title>`,
  `<meta name="description" content="${esc(S['meta.description'])}">`,
  `<meta name="theme-color" content="${THEME_COLOR}">`,
  PAGE_URL ? `<link rel="canonical" href="${esc(PAGE_URL)}">` : '<!-- No canonical link yet: set PAGE_URL in build.mjs when the final address is known. -->',
  `<meta property="og:type" content="website">`,
  `<meta property="og:locale" content="da_DK">`,
  `<meta property="og:site_name" content="${esc(name)}">`,
  `<meta property="og:title" content="${esc(S['meta.title'])}">`,
  `<meta property="og:description" content="${esc(S['meta.description'])}">`,
  PAGE_URL ? `<meta property="og:url" content="${esc(PAGE_URL)}">` : '',
  photo && PAGE_URL ? `<meta property="og:image" content="${esc(abs(photo.og.url))}">\n<meta property="og:image:width" content="${photo.og.w}">\n<meta property="og:image:height" content="${photo.og.h}">\n<meta property="og:image:alt" content="${esc(S['photo.alt'])}">` : '',
  `<link rel="icon" href="data:,">`,
  ...FONTS.filter((f) => f.preload).map((f) => `<link rel="preload" href="fonts/${f.file}" as="font" type="font/woff2" crossorigin>`),
  `<script>/* no-js -> js; ?nojs=1 previews the page without JavaScript */ if (!/[?&]nojs=1(&|$)/.test(location.search)) document.documentElement.classList.replace('no-js', 'js');</script>`,
  `<link rel="stylesheet" href="tokens.css">`,
  `<link rel="stylesheet" href="styles.css">`,
  FONTS.length ? `<style>/* The Press fonts, self-hosted (FONTS in build.mjs). The font stacks in tokens.css name them first. */\n${FONTS.map((f) =>
    `@font-face { font-family: "${f.family}"; src: url(fonts/${f.file}) format("woff2"); font-weight: ${f.weight}; font-style: normal; font-display: swap; }`).join('\n')}\n</style>` : '',
  `<script type="application/ld+json">\n${scriptJson(ld, true)}\n</script>`,
].filter(Boolean).join('\n');

const html = `<!doctype html>
<!--
  GENERATED by placeholder/build.mjs on ${buildDay}. Don't edit this file by hand.
  Change data/business.json, data/brands.json or design/copy-da.md, then run: node placeholder/build.mjs
-->
<html lang="da" data-fonts="fallback" class="no-js">
<head>
${head}
</head>
<body>

<!-- A1 status strip. Without JavaScript: a plain link to the hours (never "Åbent nu"). app.js fills in the live status. -->
<div class="sec strip">
  <a class="status label" id="status" href="#aabningstider">${esc(S['hours.heading'])}</a>
</div>

<main>
  <!-- A2 photo with the scrolling name. "hero--${photo ? photo.mode : 'none'}" is chosen by build.mjs from the photo's pixel size (ui-spec §4.3). -->
  ${heroHtml}

  <!-- A3 headline -->
  <section class="sec intro" aria-labelledby="overskrift">
    <p class="eyebrow label dot">${esc(S['hero.eyebrow'])}</p>
    <h1 id="overskrift">${esc(S['hero.headline'])}</h1>
    <p class="lede">${esc(S['hero.intro'])}</p>
  </section>

  <!-- A4 buttons -->
  <div class="grid ctas" style="--cta-count: ${ctas.length}">
    ${ctas.join('\n    ')}
  </div>

  <!-- A4 hours, contact, address -->
  <div class="sec grid info">
    <section class="cell cell--hours" aria-labelledby="aabningstider">
      <h2 id="aabningstider">${esc(S['hours.heading'])}</h2>
      ${notice}
      <table class="table hours" id="hours" aria-labelledby="aabningstider">
        <tbody>
          ${hoursRows}
        </tbody>
      </table>
      <p class="small hours-source">${esc(S['hours.source'])}</p>
    </section>
    <section class="cell" aria-labelledby="kontakt">
      <h2 id="kontakt">${esc(S['contact.heading'])}</h2>
      <table class="table details" aria-labelledby="kontakt">
        <tbody>
          <tr><th scope="row">${esc(S['contact.phone.label'])}</th><td>${phoneLink('inline-link')}</td></tr>
          ${email ? `<tr><th scope="row">${esc(S['contact.email.label'])}</th><td>${mailLink('inline-link')}</td></tr>` : ''}
        </tbody>
      </table>${email ? '' : `\n      <p class="email-missing">${esc(S['contact.email.missing'])}</p>`}
    </section>
    <section class="cell stack" aria-labelledby="findos">
      <h2 id="findos">${esc(S['address.heading'])}</h2>
      <address>${esc(street)}<br>${esc(postalCode)} ${esc(city)}</address>
      <p class="textlink-wrap"><a class="textlink hit" href="${esc(mapsUrl)}"><span>${esc(S['cta.directions'])}</span></a></p>
    </section>
  </div>

  <!-- A5 brands -->
  <section aria-labelledby="maerker">
    <div class="sec title-row">
      <h2 id="maerker">${esc(S['brands.heading'])}</h2>
      <p class="lede">${esc(S['brands.intro'])}</p>
    </div>
    <div class="sec">
      <ul class="grid brand-grid${n >= MANY_BRANDS ? ' brand-grid--many' : ''}">
        ${brandItems.join('\n        ')}
      </ul>
    </div>
  </section>

  <!-- A6 wordmark (on Shopify this slot is the theme's password section with the newsletter) -->
  <div class="sec wordmark-row">
    ${wordmark}
  </div>
</main>

<!-- A7 footer -->
<footer>
  <div class="grid foot">
    <div class="cell"><p>${esc(S['footer.text'])}</p></div>
    <div class="cell"><address>${esc(name)}<br>${esc(street)}<br>${esc(postalCode)} ${esc(city)}</address></div>
    <div class="cell"><ul><li>${phoneLink('inline-link')}</li>${email ? `<li>${mailLink('inline-link')}</li>` : ''}</ul></div>
    <div class="cell"><ul>${socials.map(([k, u]) => `<li><a class="menu-link" href="${esc(u)}">${SOCIAL_LABELS[k]}</a></li>`).join('')}</ul></div>
  </div>
  <p class="small legal">${esc(b.legalName || name)}${b.cvr ? ` · CVR ${esc(b.cvr)}` : ''}</p>
</footer>

<script type="application/json" id="hours-data">${scriptJson(hoursData)}</script>
<script src="app.js"></script>
</body>
</html>
`;

stopIfErrors();
// Fonts: build/fonts/ is an exact copy of assets/fonts/ (old files are removed).
const OUT_FONTS = join(OUT, 'fonts');
mkdirSync(OUT_FONTS, { recursive: true });
const fontFiles = existsSync(FONT_DIR) ? readdirSync(FONT_DIR).filter((f) => !f.startsWith('.')) : [];
for (const f of readdirSync(OUT_FONTS)) if (!fontFiles.includes(f)) unlinkSync(join(OUT_FONTS, f));
for (const f of fontFiles) copyFileSync(join(FONT_DIR, f), join(OUT_FONTS, f));
writeFileSync(join(OUT, 'index.html'), html);
writeFileSync(join(OUT, 'tokens.css'), `/* GENERATED copy of design/tokens.css, made by build.mjs. Edit design/tokens.css, not this file. */\n${tokensCss}`);

/* ---------- 6. Report ---------- */

const size = (f) => readFileSync(join(OUT, f)).length;
const gz = (f) => gzipSync(readFileSync(join(OUT, f))).length;
const text = ['index.html', 'tokens.css', 'styles.css', 'app.js'];
const textBytes = text.reduce((a, f) => a + size(f), 0), textGz = text.reduce((a, f) => a + gz(f), 0);
const logoBytes = pngLogoFiles.reduce((a, f) => a + size(`img/${f}`), 0);
const fontBytes = FONTS.reduce((a, f) => a + size(`fonts/${f.file}`), 0);   // all three are used (700 = today's row)
log(`\nBygget / built: placeholder/build/index.html  (${buildDay}, ${TIME_ZONE})`);
log(`  brands: ${n} logos${n >= MANY_BRANDS ? ' (many-grid)' : ''}, tile spans 2/4/6 cols: ${span(2)}/${span(4)}/${span(6)}`);
log(`  hours: ${special.length} coming special date(s)`);
if (photo) {
  log(`  photo: ${photo.w}×${photo.h} → ${photo.mode}${photo.mode === 'contained' ? ` (cap ${photo.cap}px)` : ''}; widths ${photo.widths.join(', ')}; formats ${photo.formats.join(' + ')}`);
  // Weight with the photo version most screens load (the <img src> width).
  const pf = (ext) => { const f = `img/photo-${photo.hash}-${photo.srcW}.${ext}`; return existsSync(join(OUT, f)) ? size(f) : 0; };
  const avif = pf('avif'), jpg = pf('jpg') || size(photo.src);
  log(`  page weight (photo at ${photo.srcW}px, uncompressed): HTML+CSS+JS ${kb(textBytes)} (${kb(textGz)} gzipped) + fonts ${kb(fontBytes)} + logos ${kb(logoBytes)} + photo ${avif ? `${kb(avif)} AVIF / ` : ''}${kb(jpg)} ${photo.formats.at(-1)}`);
  log(`  total: ${avif ? `${kb(textBytes + fontBytes + logoBytes + avif)} with AVIF, ` : ''}${kb(textBytes + fontBytes + logoBytes + jpg)} with ${photo.formats.at(-1)}`);
}
if (missing.length) log(`\n  [MANGLER] shown on the page for: ${missing.join(', ')}`);
if (warnings.length) { log(`\n  Advarsler / warnings (${warnings.length}):`); warnings.forEach((w) => log(`  - ${w}`)); }
log('');
